# Generated by Django 3.2.4 on 2021-06-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('severity', models.CharField(max_length=30)),
                ('cvss', models.CharField(max_length=30)),
                ('publication_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
